### ISSUE TITLE
reloading page asks if you want to save

### ISSUE THREAD

**Issue by Namaskar-1F64F** [SvenWritesCode/SplitCaptain#18]
<img width="372" alt="image" src="https://user-images.githubusercontent.com/7458951/104617241-d4a6b680-5650-11eb-9064-d4c9b2f558a1.png">
probably related to the thing being a form ?

**Comment by RusseII** [comment]
thats fun

**Comment by RusseII** [comment]
I removed the form so this should be fixed.
